### ISSUE TITLE
请问下参数【获取内容页数】具体是指的什么呢？

### ISSUE THREAD

**Issue by Sansming** [seanhuai/tumblr-source-list#2]
app.py username xxxxx photo 1
limit参数输入1，发现并不是只获取了第一页的图片，还获取到了第二页，第三页的部分图片。

**Comment by seanhuai** [comment]
limit是后台获取的页数，大概是1页兑20篇贴子。由于汤不热允许博主设置每页显示数目，所以和实际显示的前台页数不同。而且，大部分博客的一个前台页面里不全是同一类型...所以...嗯...
记住1页20帖就好了
